name: Generate PDFs

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git repository
        uses: actions/checkout@v4

      - name: Compile Problems
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            constitution.tex
          work_in_root_file_dir: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Constitution
          path: constitution.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            constitution.pdf
